name: Release
permissions:
  contents: write
  actions: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            build_cmd: pnpm build:mac
            artifacts: dist/*.dmg
          - os: ubuntu-latest
            build_cmd: pnpm build:linux
            artifacts: |
              dist/*.AppImage
              dist/*.deb
          - os: windows-latest
            build_cmd: pnpm build:win
            artifacts: dist/*.exe

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: ${{ matrix.build_cmd }}
        env:
          # These are used by electron-builder
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.artifacts }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
